# Generated by Django 6.0.3 on 2026-03-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_snackitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='snackitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='snacks/'),
        ),
    ]
