# Generated by Django 6.0.3 on 2026-04-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackitem',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
