# Generated by Django 6.0.3 on 2026-04-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_snackitem_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
